# Generated by Django 5.1.7 on 2025-04-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='stock_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
