# Generated by Django 5.1.6 on 2025-03-22 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_warehouse_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_name', models.CharField(max_length=50)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='api.warehouse')),
            ],
            options={
                'db_table': 'shelf',
            },
        ),
    ]
