# Generated by Django 5.1.6 on 2025-03-22 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_product_barcode_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='warehouse',
        ),
    ]
