# Generated by Django 5.1.6 on 2025-03-22 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_purchase_warehouse_alter_productvariant_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='warehouse',
        ),
    ]
