# Generated by Django 5.1.6 on 2025-03-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
