# Generated by Django 5.1.6 on 2025-03-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_customer_phone_number2'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('delivery_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_name', models.CharField(max_length=100)),
                ('car_number', models.CharField(max_length=100)),
                ('delivery_number', models.IntegerField(blank=True, null=True)),
                ('estimated_delivery_time', models.DurationField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
