# Generated by Django 5.1.6 on 2025-03-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_deliverymethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymethod',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='deliverymethod',
            table='delivery_methods',
        ),
    ]
