# Generated by Django 5.1.6 on 2025-04-07 08:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_customer_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='deliverymethod',
            name='date',
        ),
        migrations.RemoveField(
            model_name='deliverymethod',
            name='id',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='delivery_method_id',
            field=models.AutoField(default='CUST-DEFAULT', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='invoice_item',
            field=models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            to='api.InvoiceItem',
            null=True,
            blank=True
        ),
        ),
        migrations.AlterField(
            model_name='customer',
            name='order_history',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='car_number',
            field=models.CharField(default='CUST-DEFAULT', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='delivery_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('quotation', 'Quotation')], default='invoice', max_length=20),
        ),
    ]
